## SLURM PROLOG ###############################################################
##    Job ID : 11502134
##  Job Name : run_mult2
##  Nodelist : node2412
##      CPUs : 40
##   Mem/CPU : 2800 MB
## Directory : /oscar/home/jnickla1/fair-calibrate
##   Job Started : Fri May 16 08:01:44 PM EDT 2025
###############################################################################
>>> Constraining with cutoff year = 1930
####  • constraining/01_constrain-gsat-rmse-only.py####
0
Doing RMSE constraint...
Passing RMSE constraint: 801437
[714503 435687 111712  99079 512133 716712 617009 735234 647423 166120]
[0.16999943 0.16999965 0.16999972 0.16999974 0.1699998  0.16999981
 0.16999988 0.16999989 0.1699999  0.16999998]
[0.08715941 0.08797517 0.08815895 0.08849115 0.08933279 0.08980789
 0.09003873 0.0900814  0.09013654 0.09029503]
####  • constraining/02_run-1pct.py####
23
Running 1pctCO2 scenarios...
####  • constraining/03_reweight-rmse-posterior-multiple-constraints.py####
1072
Doing reweighting...
Traceback (most recent call last):
  File "/oscar/home/jnickla1/fair-calibrate/input/fair-2.1.3/v1.4/all-2022_hadcrut5_current/constraining/./03_reweight-rmse-posterior-multiple-constraints.py", line 51, in <module>
    temp_in = np.load(
              ^^^^^^^^
  File "/users/jnickla1/.conda/envs/fair-calibrate/lib/python3.11/site-packages/numpy/lib/_npyio_impl.py", line 451, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../../../../output/fair-2.1.3/v1.4/all-2022_hadcrut5_currentcut1930/prior_runs/temperature_1850-2101.npy'
ERROR in constraining/03_reweight-rmse-posterior-multiple-constraints.py for cutoff 1930
